package main

import (
	"my-go-app/app/exchange-rate/api/v1/router"
	_ "my-go-app/docs"
	// _ "github.com/swaggo/http-swagger/example/go-chi/docs" // docs is generated by Swag CLI, you have to import it.
)

//	@title			My Go App API
//	@version		1.0
//	@description	This is a simple app when learning Go

//	@contact.name	Tony Li
//	@contact.url	https://github.com/tonyltf
//	@contact.email	tingfung.tony@gmail.com

//	@BasePath	/v1

func main() {
	router.RunRouter()
}
