package main

import (
	"fmt"
	"net/http"
	"os"

	_ "my-go-app/docs"

	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
	httpSwagger "github.com/swaggo/http-swagger"
	// _ "github.com/swaggo/http-swagger/example/go-chi/docs" // docs is generated by Swag CLI, you have to import it.
)

// @title My Go App API
// @version 1.0
// @description This is a simple app when learning Go

func main() {
	r := chi.NewRouter()
	r.Use(middleware.RequestID)
	r.Use(middleware.Logger)
	r.Use(middleware.Recoverer)

	port := os.Getenv("PORT")
	if port == "" {
		port = "80"
	}

	r.Mount("/swagger", httpSwagger.WrapHandler)
	r.Get("/swagger/*", httpSwagger.Handler(
		httpSwagger.URL("http://localhost:"+port+"/swagger/doc.json"),
	))

	r.Get("/", func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("hello world"))
	})

	fmt.Println("Running server at port " + port)
	err := http.ListenAndServe(":"+port, r)
	if err != nil {
		fmt.Println(err)
	}
}
