basePath: /v1
info:
  contact:
    email: tingfung.tony@gmail.com
    name: Tony Li
    url: https://github.com/tonyltf
  description: This is a simple app when learning Go
  title: My Go App API
  version: "1.0"
paths:
  /healthcheck:
    get:
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Health checking
swagger: "2.0"
