basePath: /v1
info:
  contact:
    email: tingfung.tony@gmail.com
    name: Tony Li
    url: https://github.com/tonyltf
  description: This is a simple app when learning Go
  title: My Go App API
  version: "1.0"
paths:
  /healthcheck:
    get:
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Health checking
  /price/{exchange_pair}:
    get:
      parameters:
      - description: Currency Pair
        in: path
        name: exchange_pair
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: number
        "404":
          description: Not found
          schema:
            type: string
      summary: Get the last price
swagger: "2.0"
